### PR TITLE
Reworked widget plugin system and fixed minor issues

### PR DESCRIPTION
**Pull request by cli-ish**
Reworked plugin system and fixed minor issues.

### Basic
1. rewrite class loading, utilize the moodle namespaces.
2. added privacy provider for local_accessibility_configs
3. changed settings.php get_string to new lang string for better loading time.
4. implemented extra interface for widget plugins apply_style, makes life easier.

### Somewhat security releveant
1. Self xss over webservice local_accessibility_savewidgetconfig, since protected with sesskey not as important but was fixed anyway.
2. File resetall.php used PARM_URL should be PARM_LOCALURL even when its protected with a sesskey.
3. File manageenabledwidgets.php misses sesskey, allows partial management of widgets by tricking an admin to visit a url.

### Additional
Since the widget plugins needed some rework too. We created a branch here: https://github.com/sudile/moodle-local_accessibility/tree/master-with-widgets. I was unable to create a PR for it since there are only tags for the widgets repo. The base for the `master-with-widgets` branch was `v1.0.3-with-widgets` and should be merged too to a new tag too.

If there is any question feel free to ask.

Kind regards

### CODE REVIEW

**Comment by cli-ish** [comment]
Hello @ponlawat-w,

if something is missing, I am happy to provide additional explanations.

**Comment by ponlawat-w** [comment]
Hi @cli-ish, thank you for your pull request, and apologise for my late response.
I'll need sometime to fix CI issue, and then I'll look into the deeper details of your commit.

Regarding widget plugins, each of them has their own GitHub repositories, so feel free to create a pull request there:
- https://github.com/ponlawat-w/moodle-accessibility_backgroundcolour
- https://github.com/ponlawat-w/moodle-accessibility_fontface
- https://github.com/ponlawat-w/moodle-accessibility_fontsize
- https://github.com/ponlawat-w/moodle-accessibility_textcolour

Thank you so much.

**Comment by cli-ish** [comment]
Hi @ponlawat-w, 
I create the PR for each subplugin like you suggested.
If there are any issue let me know :)

**Comment by ponlawat-w** [comment]
Hi @cli-ish, thank you again for your contribution.
I have run the changes locally and see no problems, so I think we can have this as a part of next version of the plugin.

The latest support version of this plugin is Moodle 4.3, I am planning to look and combine this change with pull request #14 as well to support Moodle 4.4.

Regarding your changes, however, after running [Moodle code checker](https://github.com/moodlehq/moodle-local_codechecker/issues), it reported the following. If possible, could you please make an update to this PR to solve the following messages? (The report also includes two widget plugins that would need to be updated in the pull requests of their repositories respectively.) Thank you very much.

```
Total: 6 error(s) and 2 warning(s)

local/accessibility/classes/privacy/provider.php
#166: }
File must end with a newline character (Generic.Files.EndFileNewline.NotFound)

local/accessibility/classes/widgets/apply_style.php
#26: interface·apply_style·{
Missing docblock for interface apply_style (moodle.Commenting.MissingDocblock.Interface)
#27: ····public·function·apply_style():·string;
Missing docblock for function apply_style (moodle.Commenting.MissingDocblock.Function)

local/accessibility/lib.php
#277: ····/**·@var·\moodle_page·$PAGE·*/
Inline doc block type-hinting for '$PAGE' does not match next code line '$widgetinstances...' (moodle.Commenting.InlineComment.TypeHintingMatch)

local/accessibility/settings.php
#30: ····$ADMIN->add('modules',·new·admin_category('accessibilitywidgets',·new·lang_string('accessibilitywidgets',·'local_accessibility')));
Line exceeds 132 characters; contains 135 characters (moodle.Files.LineLength.TooLong)

local/accessibility/styles.php
#25: require_once(__DIR__·.·'/../../config.php');
Expected login check (require_login, require_course_login, require_admin, admin_externalpage_setup) following config inclusion. None found. (moodle.Files.RequireLogin.Missing)

local/accessibility/widgets/backgroundcolour/classes/backgroundcolour.php
#64: ····public·function·apply_style():·string·{
Missing docblock for function apply_style (moodle.Commenting.MissingDocblock.Function)

local/accessibility/widgets/textcolour/classes/textcolour.php
#64: ····public·function·apply_style():·string·{
Missing docblock for function apply_style (moodle.Commenting.MissingDocblock.Function)
```

PS: The release of a new version of this plugin relies on Moodle Plugin CI with GitHub Actions. Unfortunately, [there is currently an issue with Moodle Plugin CI](https://github.com/moodlehq/moodle-plugin-ci/issues/309) that makes GitHub actions workflow to fail, we might need to wait until the issue is solved before we can release a new version.

**Comment by cli-ish** [comment]
Hi @ponlawat-w,

don't know exactly how these slipped my attention i am sorry. I create a commit for this PR and the PR's in https://github.com/ponlawat-w/moodle-accessibility_backgroundcolour/pull/7 and https://github.com/ponlawat-w/moodle-accessibility_textcolour/pull/3.

If there are any more issues feel free to ask :)

**Comment by ponlawat-w** [comment]
Thank you @cli-ish, I have merged the changes and included them into version 2.0.

**Pull request merged**
